// flow-typed signature: 149624e306c2b25b779570e8ca431f49
// flow-typed version: <<STUB>>/koa-router_v^7.2.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-router'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-router' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-router/lib/layer' {
  declare module.exports: any;
}

declare module 'koa-router/lib/router' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-router/lib/layer.js' {
  declare module.exports: $Exports<'koa-router/lib/layer'>;
}
declare module 'koa-router/lib/router.js' {
  declare module.exports: $Exports<'koa-router/lib/router'>;
}
