// flow-typed signature: c9f04e3c9b2782f34297fabc9e51f566
// flow-typed version: <<STUB>>/koa-passport_v^3.0.0/flow_v0.47.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'koa-passport'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'koa-passport' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'koa-passport/lib/framework/koa' {
  declare module.exports: any;
}

declare module 'koa-passport/lib/framework/request' {
  declare module.exports: any;
}

declare module 'koa-passport/lib/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'koa-passport/lib/framework/koa.js' {
  declare module.exports: $Exports<'koa-passport/lib/framework/koa'>;
}
declare module 'koa-passport/lib/framework/request.js' {
  declare module.exports: $Exports<'koa-passport/lib/framework/request'>;
}
declare module 'koa-passport/lib/index.js' {
  declare module.exports: $Exports<'koa-passport/lib/index'>;
}
